language: python
python:
- '3.6'
install:
- pip install .
script: pytest
deploy:
  provider: pypi
  user: jhigueras
  password:
    secure: YaaJJ6iqBQme5SC4NgPK/vEweDe6iiKClNBYbq/4iafZLJUdj222Dpb27qYjspct0zxm9+hzi9Ls0npe6+B2+l4AAkK7jH2DvQVu2f7hPhn6U54G7Uck2r2VtRBGbY3cjRd3vdZT3s96wVQkFjn94msBthVbkVaeMNuaWfY+96MS6MWHGS5CrN97gHUyKyss0qmESw0jHvW8SHONVOC7gTQabdOGwTiUjKYn9Giq6psqoZB/ErcD+yLRj4FJ92zk9mp6bSWKjmRkHSCnPc9GcuaGfG2lMSHdZ7RATxTyQ2R9nWrSPlhAr+2NPZLQlBrpflzrIzD+VOAgOZMl1Xwmmmuf+kwFWE7zXzvo+yVroOTyc31QObPVlZBbOK/qzsM0s0nKF2jtMnzIFLHPOO3OTMwYe1wZamvvDzXnid8S/ssujCkwx4evYikpxpxbYMF2wZP7RLZd58f0NUai2mxz8ni5zMgs9Wre/KvtNTLCktjRGkiXJNZ2wcwIgOFBgCiwOo0boCL2kKvQg8R5s+rwrysaSNGGcTWK+8Gpis+FzOL8fFdPpk57Nzk4lFJxqAwVCWt3eG4ophfvgWB/zHodP6Wq/ysM5FPsbL/GpDKm455WKXRa376KIsOv3IgRU1VT5ns3ceeco3Ynw9g7f4lcnyxgKQmRPEwDkj4mU+C5fg4=
