language: python
python:
- '3.6'
install:
- pip install .
script: pytest
deploy:
    provider: pypi
    user: jhigueras
    password:
        secure: DlmiAV+MKyjM67mZeGmmiTg1E2TFUjZJQVZ2749tQqRzpwmVZmZplqoJaYp4xNs0HKDh99pORgmghcsCDlxL1IZs7MmF9SJQPd0m+nv1Ex4QWhJhx4avur2MNyuB7WqD3qj0E7+d9lUF7gB6QsFzjMyuK+YWgbM5qJ2zQ7iXWNt7kiJmRsD3cHhxBK8VFFE49uc8DZYzW1MkGXUL21rhKbjsrOH45gyuezgg4xUYFYSR8uDOldJBDlYinYtQD6H4Xwr1jgV12Oz/i+fS3fovnOHYrghJoybP2h6tU2Fex/CO9FW3Rhkcj51pVPYRwfsyhJZraYUTzQ9pB17fJYezVAKGHZO7VGXrZlT/WGUEwjwWeYzL8QqUNymaP4symTZHBEgyzElW8OYcL9AXjholMYcB+0hPPMC3xX+A+IjKVQOr6DLcje4ePfS3iWR5/TVB3WOwAsYYdU2NQCzXohAj7JIpHIc/USwMl9dAnfXx8Q1ZsM9NvCyk6wVDDPoACmaMAP05W15gBq8YKglRR5tfjR69Y6dP2mRWzRtGtEM4jwSKiY1uRdMceabgCtjkgL4g+XgKuPEyRtMrimQUxmGk24oGTSB0mOJvwOaTi3YkAcRrWGEjGg196SuM6VWWHGddYMzmUVlUPNvhC1zvAaYAbgG+1ECbIJ9Iy8suyJmE+Ko=
