language: python
python:
- '3.6'
install:
- pip install .
script: pytest
deploy:
  provider: pypi
  user: jhigueras
  password:
    secure: AH5mZdMj0T/WaQ6E3IVUkPrk/MhGQsK2k2QyLFF5ZJ4rAH/TTxLAPAVoY0NxKrUhd4HfojTsXPLm7GVsR4Hv5QN/iDTu/xBgnw8KlYfQMZRzXP7cMhy7kyzP9ejBnkXtAmjYMErTS7eLyJk/A3eRQu3sF6LBYC2bys0wnLDIkQT+zngsov7aFgAEQrg2cXYJ1SNNz3oyDuhPvFgeGHSBMZD8JCoAUmghHIhd124m+9cu1k6GfdaFH6HBZZGdx8huX2dfX2dK6g2q6suzvkFGj0JD8yR4W1S+1aOb+hnsqJqWeQRQ8tTFsJ6zfb6qWuoKEPyk6CROKZy9KNSx6HL8nIyR/y0uD6MN9R1zazbVqui2ELmfy3sedtchFyV7wrJZk4gBGBJf67JIE9aFar8R6x+v8kUxC6InPGd7Pw8syzekuSeeEARI040qFsV7L4LflcPKNJiW1qLe4go1c300htS6GHC13st/gjecHAnms/2AZfvjmBa4A2pIM4TS+1D8pC3r9msZpzCLe2Hzjn++xCX95LFDj1YPK+SiveBORsNh4+vDAifuUMKz6voXg1wwxJ7yZd5jVH6OFxyuDg2sKKndU0utep9yNLNokzesf8fKjQLpyNakGyOmIZDNLWdWoD8sMnIawOPBHXhaSnHUENoRrdGdHHmL+VhTZqBERk4=
