language: python
python:
- '3.6'
install:
- pip install .
script: pytest
deploy:
  provider: pypi
  user: jhigueras
  password:
    secure: "K93kA54Fgf3oqq+8QyUUu2aEOth4tPE+8RYqVObc8asjG+bd5iOTxpbk3E+JtHLiogZcjWMCbCpep8Uhy5FXkaHvfDyiMWe1l2ugO+MTTCG/MY1XtD++Q1Y804rvzTFUB4YmOpCRPp9HAKzrKjSEn6PUSVYDBAuNOGA2lHM80dSjkvECriWFcwAWfdvTuR0IhOl++Nlwh7m6cohGEz3EFwocCScXX4fYQT70XbTdaekHh6q5rS07RYqenHz9tNdviaOR6bVwVK78xfBggBv3zDQJ6gcmBvApa2eVjgvP/tHz1/0uOCGIckw6iQ5vvpfQa0A6D41/GjwG2YMjOPnfimIxXYlqzGj5nwouQcGnlBzliRuhvSmrayM4heDsVEgguJ9VKQdt1OeaOyg3rJeRTA3zgNzIofvy65qa46UBOTHxZgE0yTSs0jKJ4QlDu03pL0LkPp3eSYzWOOU2voIodsuoMYUDmgFc8G2SJ48nrZpWhaVC1JWIPaJnSmLltu0jYxkC+5eR+WKO+pTGbUfx9xetUr2txS0gZOBVA3cmu+dpQfW47jn86sPAQ1S7uivCYEzzQWdp9+UkO4Yi15KAXE6D/976a4y85GlkHQHx1S0aVAmOV4h9son07cDhHFuUGAi9ctmyp5PIC51ZctU6mrO4OjBWxOj6kBX7+tYk+UY="
